### ISSUE TITLE
Insert manually triggers and actions for all services

### ISSUE THREAD

**Issue by destgub** [burkybang/Better-IFTTT-UI#1]
It would be great if it was possible to insert the related triggers and actions on the page of each service. Even if they were to be written manually for each page of service...
for example:

Android Battery
trigger
Battery drops below 15%
Device is plugged in
Device is unplugged

action
None

If you can do it I can report all triggers and actions of my services, if everyone does their part we reconstruct the entire list.

**Comment by burkybang** [comment]
Really great idea! I've determined an automated way to accomplish this using IFTTT's internal API. Here are some screenshots of how it looks so far.

https://imgur.com/a/GMHVMAj

**Comment by burkybang** [comment]
I've pushed this new feature in version 1.6. It's already out for Firefox, but we'll need to wait for Google to approve the update for Chrome.
