### ISSUE TITLE
"Read your browsing history" permission

### ISSUE THREAD

**Issue by andyconlin** [burkybang/Better-IFTTT-UI#2]
Hi @burkybang! I really like what you're doing with this. The navigation menu is definitely needed in the UI. Thank you for putting this together. And for open-sourcing it!

[It seems](https://developer.chrome.com/extensions/permission_warnings#view_warnings) the "Read your browsing history" permission notice is generated due to the `tabs` permission in the manifest. The note in `background.js` says:
```// Inject content scripts into relevant tabs upon install```
I'm only mildly familiar with chrome extension development; is this `chrome.tabs` API only needed for the scenario(s) where [one of these](https://developer.chrome.com/apps/runtime#event-onInstalled) occurs (e.g., just installed the extension) and an `https://*.ifttt.com/*` page is _already_ open?

If that bit of code wasn't there (`background.js` lines 22-35), would a simple refresh be sufficient to activate the extension on those pages?

Thanks!

**Comment by burkybang** [comment]
Hi Andy. I just looked through the code again because I needed to refresh my memory, and I believe you are correct.
